### ISSUE TITLE
Idea - Haystack "State"

### ISSUE THREAD

**Issue by Sammyjo20** [Sammyjo20/laravel-haystack#10]
I just thought of a great idea for a feature in Haystack. I could introduce a JSON column to the Haystack model for state that can be stored and passed down into every job. This could be useful if you're using haystack in a pipeline style where the next job relys on some data that is set in the state of a previous job.

```php
// Job A:
$this->addHaystackData('name', 'Sam', 'laravel-cast')

$this->addHaystackData('data', ['foo' => 'bar'], 'array')
```

```php
// Job B
$this->getHaystackData('name') // Sam

$this->getHaystackData('data') // ['foo' => 'bar']
```

**Comment by JustSteveKing** [comment]
This could be really powerful! Especially if the jobs can mutate the haystack state?

**Comment by Sammyjo20** [comment]
Yes exactly!!

**Comment by imClement** [comment]
While the main use of Haystack data is to be create and modified by jobs, 
I think it can be useful if we can also set some data at the build level, before any job starts. 

something like:

```php
$haystack = Haystack::build()
   ->setData('data', ['username' => 'Sammyjo20'], 'array')
   ->addJob(new RetrieveDataFromApi)
   ->addJob(new ProcessDataFromApi)
   ->addJob(new StoreDataFromApi)
   ->dispatch();
```

**Comment by Sammyjo20** [comment]
Thanks @imClement for the idea, I really like it! I’m going to add it to my todo list to take a look when I’m off holiday in a few days

**Comment by Sammyjo20** [comment]
I have created a PR for the initial data as we discussed, see #38
