### ISSUE TITLE
Haystack pauses suddenly

### ISSUE THREAD

**Issue by amaelftah** [Sammyjo20/laravel-haystack#64]
i couldn't quite reproduce the issue yet ... but right now my db uses singlestore which has this form of ids

![image](https://user-images.githubusercontent.com/17250137/203396946-8d8175bc-27f3-4fc0-9976-1fbc07793242.png)

so after pushing 400 haystack_bales or so ... suddenly I found no jobs are queued and the haystack row is stale

![image](https://user-images.githubusercontent.com/17250137/203397239-7086319e-9eec-4545-abdc-6c0c452d8979.png)

also I found some queues inside haystack_bale with delay 0

![image](https://user-images.githubusercontent.com/17250137/203400395-3500bb8e-afd1-48de-af52-72a66d2e94b4.png)

my queue configuration is **process_automatically** is set to true

also when I run $haystack->dispatchNextJob() ... it process some jobs then stop 

and inside my queue jobs ... no special thing just normal handle function and what was mentioned in the docs here

![image](https://user-images.githubusercontent.com/17250137/203397591-ad28f9c0-c540-4b43-8418-edfc153ca737.png)

would appreciate if you can guide me or point me to a direction ... so far am suspecting this line could be the issue but not sure 

![image](https://user-images.githubusercontent.com/17250137/203397801-e94dc599-809b-4fac-a8bb-875d1d6a8693.png)

my call to haystack looks like this 

```php

 Haystack::build()->withName("test")->addJob(x)->addJob(y)->withDelay(1)->allowsFailure()->dispatch();
```

**Comment by amaelftah** [comment]
a quick addition here i have managed to replicate the issue ... by running multiple queue workers for the same queue for example 

``` PHP artisan queue:work --queue=x``` for multiple times

**Comment by Sammyjo20** [comment]
Hi @amaelftah I'm really sorry for leaving this issue open for so long. I've been busy working on my other open source projects. I will review this issue again over the next few days, did you have any further updates from November?

**Comment by Sammyjo20** [comment]
At this point in time I don't think I will be able to fix this issue, I only intend to work on security fixes for Laravel Haystack moving forward. I'm extremely sorry that I wasn't able to fix this @amaelftah but I hope you were able to find a solution or alternative to Laravel Haystack that helped you with your project.
