### ISSUE TITLE
Laravel 11 Support

### ISSUE THREAD

**Issue by simaodiascosta** [Sammyjo20/laravel-haystack#88]
Hey @Sammyjo20 can you add support to Laravel 11?

Thanks!

<img width="983" alt="image" src="https://github.com/Sammyjo20/laravel-haystack/assets/46888903/c3631f8d-e3bc-478f-81e4-b31b17ebd5f4">

**Comment by Sammyjo20** [comment]
Hey, I will be adding support for Laravel 11 soon, thanks for the patience!

**Comment by Sammyjo20** [comment]
Thank you for your patience, I have now added support for Laravel 11 in v2.1
